//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDecoration.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class заказ_клиента
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public заказ_клиента()
        {
            this.состав_заказа_клиента = new HashSet<состав_заказа_клиента>();
        }
    
        public int id_заказа_клиента { get; set; }
        public Nullable<System.DateTime> дата_заказа { get; set; }
        public Nullable<System.DateTime> дата_доставки { get; set; }
        public Nullable<int> id_пункт_выдачи { get; set; }
        public Nullable<int> id_клиента { get; set; }
        public Nullable<int> код_получения { get; set; }
        public Nullable<int> id_статус_заказа { get; set; }
    
        public virtual пользователи пользователи { get; set; }
        public virtual пункты_выдачи пункты_выдачи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<состав_заказа_клиента> состав_заказа_клиента { get; set; }
    }
}
