//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDecoration.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public пользователи()
        {
            this.заказ_клиента = new HashSet<заказ_клиента>();
        }
    
        public int id_пользователя { get; set; }
        public string фио { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public int id_роли { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<заказ_клиента> заказ_клиента { get; set; }
        public virtual роли_пользоваетелей роли_пользоваетелей { get; set; }
    }
}
