//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDecoration.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class состав_заказа_клиента
    {
        public int id_состава_заказа { get; set; }
        public int id_продукции { get; set; }
        public int id_заказа_клиента { get; set; }
        public int количество { get; set; }
    
        public virtual заказ_клиента заказ_клиента { get; set; }
        public virtual продукция продукция { get; set; }
    }
}
